apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: addons
  labels:
    intent: argocd
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: inflate
          image: 712415713967.dkr.ecr.us-east-1.amazonaws.com/green-container-external/docker.io/busybox:1.36
          command: [ "sh", "-c", "sleep 7200" ]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 1
              memory: 1.5Gi
