apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapp
  namespace: tcbargo
  finalizers:
     - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: jpmc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apponapp
    repoURL: https://github.com/grv180290/forjpmc.git
    targetRevision: HEAD
